const products = [
    {
        id: 1,
        name: "JK3200 Electric Handheld Packaging Machine",
        category: "Strapping Equipment",
        price: "CAD $699",
        image: "images/product1-main.jpg",
        images: ["images/product1-main.jpg","images/product1-1.jpg","images/product1-2.jpg","images/product1-3.jpg","images/product1-4.jpg","images/product1-5.jpg"],
        video: "images/product1-video.mp4",
        shortDesc: "Portable electric strapping tool for 13-16mm PP/PET straps",
        fullDesc: "The JK3200 is a professional handheld electric strapping machine designed for mobile packaging operations.",
        specs: {"Application":"Transport","Packaging Type":"Cartons","Packaging Material":"Plastic","Voltage":"110V-220V","Driven Type":"Electric","Automatic Grade":"Automatic","Core Components":"PLC, Gear, Bearing","Warranty":"1 Year","After-sales Service":"Online Support, Video Technical Support","Machinery Test Report":"Provided","Video Outgoing-Inspection":"Provided","Key Selling Points":"Easy To Operate, High Safety Level, High Productivity, Multifunctional","Place of Origin":"China","Weight":"5.5 KG","Brand Name":"Jike","Dimension (L*W*H)":"38*13*13cm"},
        features: ["One-handed operation","Friction welding","Adjustable tension"],
        service: {warranty:"1 Year",support:"Online",customization:"Available"},
        attributes: {"Application":"Packaging","Voltage":"110V-220V"},
        description: "<h3>Product Overview</h3><p>Professional handheld strapping machine.</p>"
    },
    {
        id: 2,
        name: "Portable Mini Self-Loading Stacker 1.6m",
        category: "Stacker",
        price: "CAD $999",
        image: "images/主图-1.jpg",
        images: ["images/主图-1.jpg","images/主图-2.jpg","images/主图-3.jpg","images/主图-4.jpg","images/主图-5.jpg","images/主图-6.jpg"],
        video: "images/product2-video.mp4",
        shortDesc: "Portable mini self-loading stacker with 1.6m lifting height",
        fullDesc: "The FANGGONG Mini Electric Stacker has strong robust and classical designs.",
        specs: {"Load Capacity":"300kg","Max Height":"1600mm"},
        features: ["Maintenance free","Automatic charger","Compact design"],
        service: {warranty:"1 Year",support:"Online",customization:"Available"},
        attributes: {"Condition":"New","Origin":"China"},
        description: "<h3>Overview</h3><p>Designed for frequent lifting operations.</p>"
    },
    {
        id: 3,
        name: "Self-Loading Lifting Stacker 1000kg",
        category: "Stacker",
        price: "CAD $1,299",
        image: "images/主图-11.jpg",
        images: ["images/主图-11.jpg","images/主图-12.jpg","images/主图-13.jpg","images/主图-14.jpg","images/主图-15.jpg","images/主图-16.jpg"],
        video: "images/product3-video.mp4",
        shortDesc: "Semi-electric portable self-loading stacker 1000kg",
        fullDesc: "Small truck forklift with automatic loading electric stacker.",
        specs: {"Load Capacity":"1000kg","Max Height":"1600mm"},
        features: ["High-power motor","Safe lifting","Flexible design"],
        service: {warranty:"1 Year",support:"Online",customization:"Available"},
        attributes: {"Condition":"New","Origin":"Hebei, China"},
        description: "<h3>Overview</h3><p>Designed for efficient material handling.</p>"
    },
    {
        id: 4,
        name: "EP EPT20-ET2 Electric Pallet Truck 2 Ton",
        category: "Pallet Truck",
        price: "CAD $2,099",
        image: "images/product4new-main.png",
        images: ["images/product4new-main.png","images/product4new-2.png","images/product4new-3.jpg","images/product4new-4.png","images/product4new-5.jpg"],
        video: "images/product4new-video1.mp4",
        video2: "images/product4new-video2.mp4",
        shortDesc: "EP brand electric pallet truck, 2 ton load capacity, 115mm max lifting height",
        fullDesc: "The EP EPT20-ET2 is a professional electric pallet truck with 2000kg load capacity and 115mm max lifting height.",
        specs: {"Model Number":"EPT20-ET2","Brand Name":"EP","Load Capacity":"2000kg","Max Lifting Height":"115mm","Battery":"48V/45Ah Lithium-Ion","Voltage":"110V-220V"},
        features: ["2000kg load capacity","115mm max lifting height","48V/45Ah lithium-ion battery","Polyurethane tires"],
        service: {warranty:"3 Years",support:"Online Support",customization:"OEM, ODM, OBM Available"},
        attributes: {"Condition":"New","Type":"Electric Pallet Truck","Origin":"Zhejiang, China"},
        description: "<h3>Product Overview</h3><p>Professional electric pallet truck for efficient material handling.</p>"
    },
    {
        id: 5,
        name: "Electric 3 Ton Pallet Truck Off-Road",
        category: "Pallet Truck",
        price: "CAD $1,699",
        image: "images/product4-main.jpg",
        images: ["images/product4-main.jpg","images/product4-2.jpg","images/product4-3.jpg","images/product4-4.jpg","images/product4-5.jpg","images/product4-6.jpg"],
        video: "images/product4-video.mp4",
        shortDesc: "New electric 3 ton pallet truck with off-road tires, 120mm max lifting height",
        fullDesc: "The Jinsheng Electric 3 Ton Pallet Truck is a powerful DC motor-driven power pallet jack.",
        specs: {"Model Number":"Off-road tire automatic","Color":"Black","Load Capacity":"3.0 Ton","Max. Lifting Height":"120mm","Power Source":"DC Motor"},
        features: ["3-ton heavy-duty load capacity","Off-road tire for rugged terrain","DC motor powered"],
        service: {warranty:"1 Year",support:"Online Support, Video Technical Support",customization:"Logo Customization Available"},
        attributes: {"Condition":"New","Type":"Power Pallet Truck","Brand Name":"Jinsheng","Place of Origin":"Hebei, China"},
        description: "<h3>Product Overview</h3><p>Heavy-duty pallet truck for rugged environments.</p>"
    },
    {
        id: 6,
        name: "Scissor Lift Truck 300kg",
        category: "Material Handling",
        price: "CAD $1,699",
        image: "images/product5-main.jpg",
        images: ["images/product5-main.jpg","images/product5-2.jpg","images/product5-3.jpg","images/product5-4.jpg","images/product5-5.jpg","images/product5-6.jpg"],
        video: "images/product5-video.mp4",
        shortDesc: "Scissor lift truck with 300kg load capacity, metal structure, four-wheel design",
        fullDesc: "The HYTC Scissor Lift Truck is a heavy-duty material handling solution with 300kg load capacity.",
        specs: {"Model Number":"HYTC","Type":"Scissor Lift Trucks","Load Capacity":"300kg","Material":"Metal","Wheel":"Four-Wheel"},
        features: ["300kg load capacity","Scissor lift mechanism","Four-wheel stability","Metal mesh structure"],
        service: {warranty:"3 Years",support:"Online Support",customization:"OEM, ODM, OBM Available"},
        attributes: {"Condition":"New","Type":"Scissor Lift Trucks","Origin":"Shandong, China"},
        description: "<h3>Product Overview</h3><p>Heavy-duty scissor lift truck for versatile material handling.</p>"
    },
    {
        id: 7,
        name: "Electric Industrial Tools Climbing Steel Platform Machine 400 kg Load Capacity Foldable Auxiliary Turning",
        category: "Wheelbarrows",
        price: "CAD $1,299",
        image: "images/product7-main.jpg",
        images: ["images/product7-main.jpg","images/product7-2.jpg","images/product7-3.jpg","images/product7-4.jpg","images/product7-5.jpg","images/product7-6.jpg"],
        video: "images/product7-video1.mp4",
        video2: "images/product7-video2.mp4",
        shortDesc: "Electric stair climber with 400kg load capacity, 1200W motor, foldable steel platform",
        fullDesc: "Electric Industrial Climbing Steel Platform Machine with 400kg load capacity and 1200W motor power.",
        specs: {"Usage":"Storage, Shopping, Industrial, Tools, Other","Material":"Steel","Wheel":"Six-Wheel","Surface Treatment":"Powder Coating","Customized Support":"OEM","Motor Power":"1200W","Model Number":"LP-400-1","Type":"Wheelbarrows","Load Capacity":"400KG","Color":"Black","Power":"1200W","Frame Size":"54*110CM","Structure":"Platform","Feature":"Foldable","Warranty":"1 Year","Post Material":"Metal Steel","Place of Origin":"China","Product Name":"Electric Stair Climber","Batteries":"Lithium Battery 48V/72Ah","Voltage":"110V-220V"},
        features: ["400kg load capacity","1200W motor","Foldable steel platform","Six-wheel stair climbing","Lithium battery 48V/72Ah"],
        service: {warranty:"1 Year",support:"Online Support",customization:"OEM Available"},
        attributes: {"Condition":"New","Type":"Wheelbarrows","Load Capacity":"400KG","Origin":"China"},
        description: "<h3>Product Overview</h3><p>Electric stair climbing platform machine for heavy-duty material handling.</p>"
    },
    {
        id: 8,
        name: "Coming Soon - New Product",
        category: "Material Handling",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "Coming Soon!",
        fullDesc: "This product is currently in preparation.",
        specs: {"Status":"Coming Soon"},
        features: ["Coming Soon"],
        service: {warranty:"Coming Soon",support:"Coming Soon",customization:"Coming Soon"},
        attributes: {"Status":"Coming Soon"},
        description: "<h3>Coming Soon</h3><p>Stay tuned!</p>"
    },
    {
        id: 9,
        name: "Coming Soon - New Product",
        category: "Strapping Equipment",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "Coming Soon!",
        fullDesc: "This product is currently in preparation.",
        specs: {"Status":"Coming Soon"},
        features: ["Coming Soon"],
        service: {warranty:"Coming Soon",support:"Coming Soon",customization:"Coming Soon"},
        attributes: {"Status":"Coming Soon"},
        description: "<h3>Coming Soon</h3><p>Stay tuned!</p>"
    },
    {
        id: 10,
        name: "Coming Soon - New Product",
        category: "Material Handling",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "Coming Soon!",
        fullDesc: "This product is currently in preparation.",
        specs: {"Status":"Coming Soon"},
        features: ["Coming Soon"],
        service: {warranty:"Coming Soon",support:"Coming Soon",customization:"Coming Soon"},
        attributes: {"Status":"Coming Soon"},
        description: "<h3>Coming Soon</h3><p>Stay tuned!</p>"
    },
    {
        id: 11,
        name: "Coming Soon - New Product",
        category: "Strapping Equipment",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "Coming Soon!",
        fullDesc: "This product is currently in preparation.",
        specs: {"Status":"Coming Soon"},
        features: ["Coming Soon"],
        service: {warranty:"Coming Soon",support:"Coming Soon",customization:"Coming Soon"},
        attributes: {"Status":"Coming Soon"},
        description: "<h3>Coming Soon</h3><p>Stay tuned!</p>"
    }
];
