// Product Data - Industrial Equipment
const products = [
    {
        id: 1,
        name: "JK3200 Electric Handheld Packaging Machine",
        category: "Strapping Equipment",
        price: "CAD $699",
        image: "images/product1-main.jpg",
        images: [
            "images/product1-main.jpg",
            "images/product1-1.jpg",
            "images/product1-2.jpg",
            "images/product1-3.jpg",
            "images/product1-4.jpg",
            "images/product1-5.jpg"
        ],
        video: "images/product1-video.mp4",
        shortDesc: "Portable electric strapping tool for 13-16mm PP/PET straps",
        fullDesc: "The JK3200 is a professional handheld electric strapping machine designed for mobile packaging operations.",
        specs: {
            "Model": "JK3200",
            "Strap Width": "13-16mm",
            "Tension Force": "900-3200N",
            "Battery Life": "90 minutes"
        },
        features: ["One-handed operation", "Friction welding", "Adjustable tension"],
        service: { warranty: "1 Year", support: "Online", customization: "Available" },
        attributes: { "Application": "Packaging", "Voltage": "110V-220V" },
        description: "<h3>Product Overview</h3><p>Professional handheld strapping machine.</p>"
    },
    {
        id: 2,
        name: "Portable Mini Self-Loading Stacker 1.6m",
        category: "Stacker",
        price: "CAD $999",
        image: "images/主图-1.jpg",
        images: ["images/主图-1.jpg", "images/主图-2.jpg", "images/主图-3.jpg", "images/主图-4.jpg", "images/主图-5.jpg", "images/主图-6.jpg"],
        video: "images/product2-video.mp4",
        shortDesc: "Portable mini self-loading stacker with 1.6m lifting height",
        fullDesc: "The FANGGONG Mini Electric Stacker has strong robust and classical designs.",
        specs: { "Load Capacity": "300kg", "Max Height": "1600mm" },
        features: ["Maintenance free", "Automatic charger", "Compact design"],
        service: { warranty: "1 Year", support: "Online", customization: "Available" },
        attributes: { "Condition": "New", "Origin": "China" },
        description: "<h3>Overview</h3><p>Ideal for frequent lifting.</p>"
    },
    {
        id: 3,
        name: "Self-Loading Lifting Stacker 1000kg",
        category: "Stacker",
        price: "CAD $1,299",
        image: "images/主图-11.jpg",
        images: ["images/主图-11.jpg", "images/主图-12.jpg", "images/主图-13.jpg", "images/主图-14.jpg", "images/主图-15.jpg", "images/主图-16.jpg"],
        video: "images/product3-video.mp4",
        shortDesc: "Semi-electric portable self-loading stacker 1000kg",
        fullDesc: "Small truck forklift with automatic loading electric stacker.",
        specs: { "Load Capacity": "1000kg", "Max Height": "1600mm" },
        features: ["High-power motor", "Safe lifting", "Flexible design"],
        service: { warranty: "1 Year", support: "Online", customization: "Available" },
        attributes: { "Condition": "New", "Origin": "Hebei, China" },
        description: "<h3>Overview</h3><p>Designed for efficient material handling.</p>"
    },
    {
        id: 4,
        name: "Coming Soon - New Product",
        category: "Material Handling",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    },
    {
        id: 5,
        name: "Coming Soon - New Product",
        category: "Material Handling",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    },
    {
        id: 6,
        name: "Coming Soon - New Product",
        category: "Strapping Equipment",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    },
    {
        id: 7,
        name: "Coming Soon - New Product",
        category: "Material Handling",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    },
    {
        id: 8,
        name: "Coming Soon - New Product",
        category: "Strapping Equipment",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    },
    {
        id: 9,
        name: "Coming Soon - New Product",
        category: "Material Handling",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    },
    {
        id: 10,
        name: "Coming Soon - New Product",
        category: "Strapping Equipment",
        price: "CAD $0.00",
        image: "⏳",
        images: [],
        shortDesc: "上新中，敬请期待！",
        fullDesc: "This product is currently in preparation.",
        specs: { "Status": "Coming Soon" },
        features: ["Coming Soon"],
        service: { warranty: "Coming Soon", support: "Coming Soon", customization: "Coming Soon" },
        attributes: { "Status": "Coming Soon" },
        description: "<h3>产品上新中</h3><p>⏳ 上新中，敬请期待！</p>"
    }
];
